from pptx import Presentation
from pptx.util import Inches, Pt
import os

# ✅ Paths
base_dir = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics"
visuals_dir = os.path.join(base_dir, "visuals")
output_ppt = os.path.join(base_dir, "docs", "MGNREGA_Presentation.pptx")

# ✅ Ensure output folder exists
os.makedirs(os.path.dirname(output_ppt), exist_ok=True)

# ✅ Create a PowerPoint object
prs = Presentation()

# 🏠 Slide 1 — Title Slide
slide_title = prs.slides.add_slide(prs.slide_layouts[0])
slide_title.shapes.title.text = "MGNREGA Karnataka Analytics - FY 2023-24"
slide_title.placeholders[1].text = "Automated KPI Report generated via Python"

# 🧩 Slide 2 — Overview
slide_overview = prs.slides.add_slide(prs.slide_layouts[1])
slide_overview.shapes.title.text = "Project Overview"
content = (
    "This presentation summarizes the MGNREGA performance metrics across districts of Karnataka.\n\n"
    "Key KPIs include:\n"
    "- Total Individuals Worked\n"
    "- Total Households Worked\n"
    "- Total Expenditure and Wages\n"
    "- Average Wage Rate\n"
    "- Households Completing 100 Days of Employment"
)
slide_overview.placeholders[1].text = content

# 📊 Slide 3+ — Add visuals dynamically
charts = [
    ("Total_Individuals_Worked_top10.png", "Top 10 Districts - Individuals Worked"),
    ("Total_Individuals_Worked_bottom10.png", "Bottom 10 Districts - Individuals Worked"),
    ("Total_Households_Worked_top10.png", "Top 10 Districts - Households Worked"),
    ("Total_Households_Worked_bottom10.png", "Bottom 10 Districts - Households Worked"),
    ("Total_Exp_top10.png", "Top 10 Districts - Expenditure"),
    ("Total_Exp_bottom10.png", "Bottom 10 Districts - Expenditure"),
    ("Wages_top10.png", "Top 10 Districts - Wages"),
    ("Wages_bottom10.png", "Bottom 10 Districts - Wages"),
    ("Average_Wage_rate_per_day_per_person_top10.png", "Top 10 Districts - Avg Wage Rate"),
    ("Average_Wage_rate_per_day_per_person_bottom10.png", "Bottom 10 Districts - Avg Wage Rate"),
    ("Total_No_of_HHs_completed_100_Days_of_Wage_Employment_top10.png", "Top 10 Districts - 100 Days Completed"),
    ("Total_No_of_HHs_completed_100_Days_of_Wage_Employment_bottom10.png", "Bottom 10 Districts - 100 Days Completed")
]

for file_name, title in charts:
    img_path = os.path.join(visuals_dir, file_name)
    if os.path.exists(img_path):
        slide = prs.slides.add_slide(prs.slide_layouts[5])
        slide.shapes.title.text = title
        slide.shapes.add_picture(img_path, Inches(1), Inches(1.5), width=Inches(8))
        print(f"✅ Added slide for {title}")
    else:
        print(f"⚠️ Missing: {file_name}")

# 💡 Final Slide — Summary
slide_summary = prs.slides.add_slide(prs.slide_layouts[1])
slide_summary.shapes.title.text = "Insights Summary"
slide_summary.placeholders[1].text = (
    "1. Districts like Belagavi, Ballari, and Bagalkote show highest participation.\n"
    "2. Wage expenditure aligns closely with household engagement.\n"
    "3. Need improvement in Bengaluru & Kodagu districts.\n\n"
    "✅ Generated by: MGNREGA Analytics Automation Script"
)

# ✅ Save presentation
prs.save(output_ppt)
print("🎯 PowerPoint created successfully at:", output_ppt)
